name: 60 Days Stale Check

# **What it does**: Issues and pull requests older than 60 days will be flagged as stale unless they contain a specific label.
# **Why we have it**: We want to manage our queue of issues and pull requests.
# **Who does it impact**: Everyone that works in docs-content.

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true        
      
  

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@7fb802b3079a276cf3c7e6ba9aa003c665b3f838
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            ":wave: Thanks for contributing to the docs by opening an issue! It looks like this issue might be stale. 
            If you'd still like to see these proposed changes made, please open a new issue using 
            [this issue form](https://github.com/github/docs-content/issues/new?assignees=&labels=Improve+existing+docs&template=improve-existing-docs.yml&title=%5BImprovement%5D%3A+). 
            The issue form contains instructions for making the necessary documentation changes yourself and how to 
            request support from the Docs team."
          stale-pr-message: 'This PR has been open 60 days with no activity. Unless you take action, this PR will be closed as stale in 24 hours. If it''s closed in error, please feel free to reopen.'
          days-before-stale: 0
          days-before-close: -1
          only-labels: 'Improve existing docs'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'never-stale'
          exempt-issue-labels: 'never-stale'
